---
apiVersion: devopstoolkitseries.com/v1alpha1
kind: GitHubClaim
metadata:
  name: ${{ values.name }}
spec:
  id: ${{ values.name }}
  parameters:
    public: ${{ values.public }}
    registry: ${{ values.registry }}
    app:
      language: go
      host: my-repo.acme.com
      namespace: a-team
    db:
      enabled: true
      provider: aws
      version: "16.2"
    repo:
      user: vfarcic
    gitops:
      enabled: true
      user: vfarcic
      repo: crossplane-gh