apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: dot-github-template
  title: dot-github
  description: Create and Manage GitHub repositories
spec:
  owner: vfarcic/crossplanme-gh
  type: service
  parameters:
    - title: Whether the repo should be public
      required:
        - public
        - registry
      properties:
        public:
          type: string
          default: "true"
        registry:
          type: string
          default: ttl.sh
        appLanguage:
          type: string
          default: "go"
  steps:
    - id: log-message
      name: Log Message
      action: debug:log
      input:
        message: 'Hello, ${{ parameters.name }}!'