apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: dot-github-template
  title: dot-github
  description: Create and Manage GitHub repositories
spec:
  owner: vfarcic/crossplanme-gh
  type: service
  parameters:
    - title: General Info
      required:
        - public
        - registry
      properties:
        public:
          type: string # boolean
          default: "true"
        registry:
          type: string
          default: ttl.sh
    - title: App
      properties:
        appLanguage:
          type: string # array
          default: go
        appHost:
          type: string
          default: my-repo.acme.com
        appNamespace:
          type: string
          default: a-team
    - title: DB
      properties:
        dbEnabled:
          type: string # boolean
          default: "true"
        dbProvider:
          type: string
          default: aws # array
        dbNamespace:
          type: string
          default: a-team # array from Kubernetes
    - title: Repo
      properties:
        repoUser:
          type: string
          default: vfarcic
    - title: GitOps
      properties:
        gitOpsEnabled:
          type: string
          default: "true"
        gitOpsUser:
          type: string
          default: vfarcic
        gitOpsRepo:
          type: string
          default: crossplane-gh
  steps:
    - id: log-message
      name: Log Message
      action: debug:log
      input:
        message: 'Hello, ${{ parameters.name }}!'