apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: dot-github-template
  title: dot-github
  description: Create and Manage GitHub repositories
spec:
  owner: vfarcic/crossplanme-gh
  type: service
  parameters:
    - title: General Info 222
      required:
        - public
        - registry
      properties:
        public:
          type: string # FIXME: boolean
          default: "true"
          pattern: '^(true|false)*$'
        registry:
          type: string
          default: ttl.sh
    - title: App
      required:
        - appLanguage
        - appHost
        - appNamespace
      properties:
        appLanguage:
          type: string # FIXME: array
          default: go
        appHost:
          type: string
          default: my-repo.acme.com
        appNamespace:
          type: string
          default: a-team
    - title: DB
      required:
        - dbEnabled
        - dbProvider
        - dbNamespace
      properties:
        dbEnabled:
          type: string # FIXME: boolean
          default: "true"
        dbProvider:
          type: string
          default: aws # FIXME: array
        dbNamespace:
          type: string
          default: a-team # FIXME: array from Kubernetes
    - title: Repo
      required:
        - repoUser
      properties:
        repoUser:
          type: string
          default: vfarcic
    - title: GitOps
    - title: Repo
      required:
        - gitOpsEnabled
        - gitOpsUser
        - gitOpsRepo
      properties:
        gitOpsEnabled:
          type: string
          default: "true"
        gitOpsUser:
          type: string
          default: vfarcic
        gitOpsRepo:
          type: string
          default: crossplane-gh
  steps:
    - id: log-message
      name: Log Message
      action: debug:log
      input:
        message: 'Hello, ${{ parameters.name }}!'