apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: dot-github-template
  title: dot-github
  description: Create and Manage GitHub repositories
spec:
  owner: vfarcic/crossplanme-gh
  type: service
  parameters:
    - title: General Info 222
      required:
        - public
        - registry
      properties:
        public:
          type: string # FIXME: boolean
          default: "true"
          pattern: '^(true|false)*$'
        registry:
          type: string
          default: ttl.sh
        app:
          type: object
          properties:
            language:
              type: string
              default: go
              enum: ["go", "js"]
            host:
              type: string
              default: my-repo.acme.com
            namespace:
              type: string
              default: a-team
        db:
          type: object
          properties:
            enabled:
              type: string # FIXME: boolean
              default: "true"
              pattern: '^(true|false)*$'
            provider:
              type: string
              default: aws
              enum: ["aws", "azure", "google"]
              pattern: '^()*$'
            namespace:
              type: string
              default: a-team # FIXME: array from Kubernetes
        repo:
          type: object
          properties:
            user:
              type: string
              default: vfarcic
        gitOps:
          type: object
          properties:
            enabled:
              type: string
              default: "true"
              pattern: '^(true|false)*$'
            user:
              type: string
              default: vfarcic
            repo:
              type: string
              default: crossplane-gh
  steps:
    - id: log-message
      name: Log Message
      action: debug:log
      input:
        message: 'Hello, ${{ parameters.gitOps.user }}/${{ parameters.gitOps.repo }}!'
