---
apiVersion: devopstoolkitseries.com/v1alpha1
kind: GitHubClaim
metadata:
  name: crossplane-gh-demo
spec:
  id: crossplane-gh-demo
  parameters:
    public: true
    registry: ttl.sh
    app:
      language: go
      host: my-repo.deeps.hsh
      namespace: a-team
    db:
      enabled: false
    repo:
      user: deepdelver
    gitops:
      enabled: true
      user: deepdelver
      repo: crossplane-gh
