apiVersion: repo.github.upbound.io/v1alpha1
kind: Repository
metadata:
  name: crossplane-github-demo
spec:
  forProvider:
    name: crossplane-github-demo
    visibility: public
    hasIssues: true
---
apiVersion: repo.github.upbound.io/v1alpha1
kind: RepositoryFile
metadata:
  name: crossplane-github-demo-gitignore
spec:
  forProvider:
    commitAuthor: Crossplane
    commitEmail: github-provider@crossplane.io
    commitMessage: "Crossplane rocks"
    content: |
      /tmp
    file: .gitignore
    repositoryRef:
      name: crossplane-github-demo
---
apiVersion: repo.github.upbound.io/v1alpha1
kind: Branch
metadata:
  name: crossplane-github-demo-init
spec:
  forProvider:
    branch: init
    repositoryRef:
      name: crossplane-github-demo
