---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-deeps-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Deepdelver/crossplane-deeps-demo
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: git-repos
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
